name: Report Security Issues
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  report_security_issues:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash"
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-report_security_issues
      cancel-in-progress: true
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache: true

      - name: Install vulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Print vulncheck version
        run: govulncheck -version

      - name: Run vulnerability check
        run: govulncheck -format text -mode source -scan symbol -show verbose -test ./...
