name: Dependencies Check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: govulncheck
        uses: golang/govulncheck-action@v1
