name: Go
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go: [ "1.13", "1.14", "1.15", "1.16", "1.17" ]
        db: [ "7.0.13", "7.1.1" ]
    env:
      DEFAULT_GO: "1.17"
      DEFAULT_DB: "7.1.1"
    name: Build with go version ${{ matrix.go }} and db  ${{ matrix.db }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39

      - name: test
        env:
          DB_VERSION: ${{ matrix.db }}
        run: go test -v -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB && github.repository_owner == 'exasol'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}